#!/usr/bin/env ruby
#  Phusion Passenger - http://www.modrails.com/
#  Copyright (c) 2010 Phusion
#
#  "Phusion Passenger" is a trademark of Hongli Lai & Ninh Bui.
#
#  See LICENSE file for license information.

STDOUT.sync = true
STDERR.sync = true

require 'uri'
url = ARGV[0]
begin
	uri = URI.parse(url)
rescue URI::InvaludURIError
	STDERR.puts "*** ERROR: '#{url}' is not a valid URL."
	exit 1
end
if uri.scheme.nil? || uri.host.nil? || uri.port.nil? || uri.path.nil?
	STDERR.puts "*** ERROR: '#{url}' is not a valid URL."
	exit 1
end

require 'socket'
path = uri.path.empty? ? "/" : uri.path
socket = TCPSocket.new('127.0.0.1', uri.port)
if uri.scheme == 'https'
	require 'openssl'
	socket = OpenSSL::SSL::SSLSocket.new(socket)
	socket.sync_close = true
	socket.connect
end
begin
	socket.write("HEAD #{path} HTTP/1.1\r\n")
	socket.write("Host: #{uri.host}\r\n")
	socket.write("Connection: close\r\n")
	socket.write("\r\n")
	if socket.respond_to?(:close_write)
		socket.close_write
		socket.read
	else
		socket.readline
	end
ensure
	socket.close
end